{
  "configurations": [
    {
      "nodes": [
        {
          "cpeMatch": [
            {
              "criteria": "cpe:2.3:a:luajit:luajit:*:*:*:*:*:*:*:*",
              "matchCriteriaId": "7369364F-A393-4616-B40E-8097CA70E957",
              "versionEndIncluding": "2.0.5",
              "vulnerable": true
            },
            {
              "criteria": "cpe:2.3:a:luajit:luajit:2.1.0:beta1:*:*:*:*:*:*",
              "matchCriteriaId": "50AC5D5E-8DFE-40F5-B46D-C8F4DD038E22",
              "vulnerable": true
            },
            {
              "criteria": "cpe:2.3:a:luajit:luajit:2.1.0:beta2:*:*:*:*:*:*",
              "matchCriteriaId": "934D02F3-A619-41AF-93B0-905D9426ED03",
              "vulnerable": true
            },
            {
              "criteria": "cpe:2.3:a:luajit:luajit:2.1.0:beta3:*:*:*:*:*:*",
              "matchCriteriaId": "E5411EE3-61B9-4F24-BE5A-E57F34F30F9E",
              "vulnerable": true
            }
          ],
          "negate": false,
          "operator": "OR"
        }
      ]
    }
  ],
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c."
    },
    {
      "lang": "es",
      "value": "LuaJIT versiones hasta 2.1.0-beta3, presenta una lectura fuera de límites en la función lj_err_run en el archivo lj_err.c."
    }
  ],
  "id": "CVE-2020-24372",
  "lastModified": "2020-08-24T17:50:13.633",
  "metrics": {
    "cvssMetricV2": [
      {
        "acInsufInfo": false,
        "baseSeverity": "MEDIUM",
        "cvssData": {
          "accessComplexity": "LOW",
          "accessVector": "NETWORK",
          "authentication": "NONE",
          "availabilityImpact": "PARTIAL",
          "baseScore": 5.0,
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
          "version": "2.0"
        },
        "exploitabilityScore": 10.0,
        "impactScore": 2.9,
        "obtainAllPrivilege": false,
        "obtainOtherPrivilege": false,
        "obtainUserPrivilege": false,
        "source": "nvd@nist.gov",
        "type": "Primary",
        "userInteractionRequired": false
      }
    ],
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 7.5,
          "baseSeverity": "HIGH",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "privilegesRequired": "NONE",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 3.6,
        "source": "nvd@nist.gov",
        "type": "Primary"
      }
    ]
  },
  "published": "2020-08-17T17:15:13.987",
  "references": [
    {
      "source": "cve@mitre.org",
      "tags": [
        "Exploit",
        "Third Party Advisory"
      ],
      "url": "https://github.com/LuaJIT/LuaJIT/issues/603"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Analyzed",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-125"
        }
      ],
      "source": "nvd@nist.gov",
      "type": "Primary"
    }
  ]
}