{
  "configurations": [
    {
      "nodes": [
        {
          "cpeMatch": [
            {
              "criteria": "cpe:2.3:a:python_software_foundation:python:2.4.5:*:*:*:*:*:*:*",
              "matchCriteriaId": "00DEEEDB-98B2-43FE-A1B2-340294097399",
              "vulnerable": true
            }
          ],
          "negate": false,
          "operator": "OR"
        }
      ]
    }
  ],
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Tools/faqwiz/move-faqwiz.sh (aka the generic FAQ wizard moving tool) in Python 2.4.5 might allow local users to overwrite arbitrary files via a symlink attack on a tmp$RANDOM.tmp temporary file.  NOTE: there may not be common usage scenarios in which tmp$RANDOM.tmp is located in an untrusted directory."
    },
    {
      "lang": "es",
      "value": "Tools/faqwiz/move-faqwiz.sh (también conocido como \"la herramienta de movimiento del asistente genérico del FAQ\") en Python 2.4.5, puede que permita a usuarios locales sobrescribir ficheros de su elección a través de un ataque de enlace simbólico en un fichero temporal tmp$RANDOM.tmp. NOTA: puede que no existan escenarios de uso comunes en los que tmp$RANDOM.tmp esté localizado en un directorio que no sea de confianza."
    }
  ],
  "id": "CVE-2008-4108",
  "lastModified": "2017-08-08T01:32:25.577",
  "metrics": {
    "cvssMetricV2": [
      {
        "acInsufInfo": false,
        "baseSeverity": "HIGH",
        "cvssData": {
          "accessComplexity": "LOW",
          "accessVector": "LOCAL",
          "authentication": "NONE",
          "availabilityImpact": "COMPLETE",
          "baseScore": 7.2,
          "confidentialityImpact": "COMPLETE",
          "integrityImpact": "COMPLETE",
          "vectorString": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
          "version": "2.0"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 10.0,
        "obtainAllPrivilege": false,
        "obtainOtherPrivilege": false,
        "obtainUserPrivilege": false,
        "source": "nvd@nist.gov",
        "type": "Primary",
        "userInteractionRequired": false
      }
    ]
  },
  "published": "2008-09-18T17:59:33.093",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=498899"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://marc.info/?l=oss-security&m=122148330903513&w=2"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://marc.info/?l=oss-security&m=122152861617434&w=2"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://securityreason.com/securityalert/4274"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://www.securityfocus.com/bid/31184"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://www.securitytracker.com/id?1020904"
    },
    {
      "source": "cve@mitre.org",
      "url": "http://www.vupen.com/english/advisories/2008/2659"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=462326"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/45161"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vendorComments": [
    {
      "comment": "Not vulnerable. This issue did not affect the versions of python as shipped with Red Hat Enterprise Linux 2.1, 3, 4, or 5.\n",
      "lastModified": "2009-03-13T00:00:00",
      "organization": "Red Hat"
    }
  ],
  "vulnStatus": "Modified",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-59"
        }
      ],
      "source": "nvd@nist.gov",
      "type": "Primary"
    }
  ]
}